name: CI Test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    lint:
        runs-on: ubuntu-latest
        env:
            CI: true
            working-directory: .
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              working-directory: ${{ env.working-directory }}
              run: npm ci 
            - name: formatting
              working-directory: ${{ env.working-directory }}
              run: npx prettier src/*.ts
            # - name: test
            #   working-directory: ${{ env.working-directory }}
            #   run: npm test
            - name: build
              working-directory: ${{ env.working-directory }}
              run: npm run build
